.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GNUAIS SECTION "August 07, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gnuais \- GNU Automatic Identification System receiver
.SH SYNOPSIS
.B gnuais
.RI [ options ] 
.SH DESCRIPTION
This manual page documents briefly the
.B gnuais
command.
.PP
\fBgnuais\fP is a tool for demodulating and decoding AIS messages using the line/mic input of the sound card. Connect the discriminator output of a VHF receiver tuned to either 161.975 MHz or 162.075 MHz to the line/mic input. Then run gnuais with no options or with some of the options described below. 
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-c <filename>
Specify config file to use. If not specified, it looks for gnuais.conf in the current folder, then /etc/gnuais.conf, /usr/local/etc/gnuais.conf and /usr/etc/gnuais.conf.
.TP
.B \-f
Runs
.B gnuais
in the background.
.TP
.B \-h
Shows the short command use info.
.TP
.B \-l <filename>
Runs with raw audio data from file
.TP
.B \-s <filename>
Saves raw audio data to file
.TP
.B \-e <level>
Log level: INFO, DEBUG, NOTICE, WARNING, ERR, CRIT, ALERT, EMERG
.TP
.B \-o <dest>
Log destination: none, file, stderr, syslog.
.TP
.B \-r <dir>
Log directory
.TP
.B \-n <name>
Name of the log
.SH AUTHOR
gnuais was written by <ruben.undheim@gmail.com>.
.PP
This manual page was written by Ruben Undheim <ruben.undheim@gmail.com>,
for the Debian project (and may be used by others).
